FROM python:3.9-slim

WORKDIR /appbix

COPY requirements.txt .

RUN pip install redis celery

COPY . /app

ENV CELERY_BROKER_URL redis://redis:6379

CMD ["celery", "-A", "hotel", "worker", "-l", "info"]